name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build & Test on Ubuntu Latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests
        run: cargo test --verbose

  build-win64:
    name: Build & Test on Windows 64Bit

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-win32:
    name: Build & Test on Windows 32Bit

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1

      - name: Install 32Bit toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: i686-pc-windows-msvc

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  build-osx:
    name: Build & Test on OS-X

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
